version: '3'
services:
  postgres:
    image: postgres:14.1-alpine
    container_name: postgres
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB_NAME:-postgres}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - postgres
    ports:
      - '${PGADMIN_PORT:-8555}:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    restart: unless-stopped

  # todo: fix symlink
  # block-empire-server:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: block-empire-server
  #   depends_on:
  #     - postgres
  #   ports:
  #     - '3001:3001'
  #   restart: always

volumes:
  postgres-data:
  pgadmin-data:
